version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    restart: 'on-failure'
    environment: # //TODO: check workings its or no! //TODO
      - ASPNETCORE_ENVIRONMENT
      - SERVER_CONNECTION_STRING
    networks:
      - proxy
    # Traefik labels
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.rule=${TRAEFIK_HOST_SERVER}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.Cache-Control=no-cache"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.Pragma=no-cache"
  auth:
    build:
      context: .
      dockerfile: Auth/Dockerfile
    restart: 'on-failure'
    environment: # //TODO: check workings its or no! //TODO
      - ASPNETCORE_ENVIRONMENT
      - AUTH_CONNECTION_STRING
    networks:
      - proxy
    # Traefik labels
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.rule=${TRAEFIK_HOST_AUTH}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-secure.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.Cache-Control=no-cache"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}.headers.customrequestheaders.Pragma=no-cache"

networks:
  proxy:
    external: true